export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOG_OUT = "LOG_OUT";
export const GET_USER_PROFILE = "GET_USER_PROFILE";

export const HOME_VIDEOS_REQUEST = "HOME_VIDEOS_REQUEST";
export const HOME_VIDEOS_SUCCESS = "HOME_VIDEOS_SUCCESS";
export const HOME_VIDEOS_FAILURE = "HOME_VIDEOS_FAILURE";

export const SPECIFIC_VIDEO_REQUEST = "SPECIFIC_VIDEO_REQUEST";
export const SPECIFIC_VIDEO_SUCCESS = "SPECIFIC_VIDEO_SUCCESS";
export const SPECIFIC_VIDEO_FAILURE = "SPECIFIC_VIDEO_FAILURE";

export const RELATED_VIDEO_REQUEST = "RELATED_VIDEO_REQUEST";
export const RELATED_VIDEO_SUCCESS = "RELATED_VIDEO_SUCCESS";
export const RELATED_VIDEO_FAILURE = "RELATED_VIDEO_FAILURE";

export const SEARCH_VIDEO_REQUEST = "SEARCH_VIDEO_REQUEST";
export const SEARCH_VIDEO_SUCCESS = "SEARCH_VIDEO_SUCCESS";
export const SEARCH_VIDEO_FAILURE = "SEARCH_VIDEO_FAILURE";

export const CHANNEL_DETAILS_REQUEST = "CHANNEL_DETAILS_REQUEST";
export const CHANNEL_DETAILS_SUCCESS = "CHANNEL_DETAILS_SUCCESS";
export const CHANNEL_DETAILS_FAILURE = "CHANNEL_DETAILS_FAILURE";
export const CHANNEL_VIDEOS_REQUEST = "CHANNEL_VIDEOS_REQUEST";
export const CHANNEL_VIDEOS_SUCCESS = "CHANNEL_VIDEOS_SUCCESS";
export const CHANNEL_VIDEOS_FAILURE = "CHANNEL_VIDEOS_FAILURE";

export const CHANNEL_SUBSCRIPTION_STATUS_REQUEST =
  "CHANNEL_SUBSCRIPTION_STATUS_REQUEST";
export const CHANNEL_SUBSCRIPTION_STATUS_SUCCESS =
  "CHANNEL_SUBSCRIPTION_STATUS_SUCCESS";
export const CHANNEL_SUBSCRIPTION_STATUS_FAILURE =
  "CHANNEL_SUBSCRIPTION_STATUS_FAILURE";

export const FETCH_COMMENTS_REQUEST = "FETCH_COMMENTS_REQUEST";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const FETCH_COMMENTS_FAILURE = "FETCH_COMMENTS_FAILURE";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILURE = "ADD_COMMENT_FAILURE";

export const USER_SUBSCRIPTIONS_REQUEST = "USER_SUBSCRIPTIONS_REQUEST";
export const USER_SUBSCRIPTIONS_SUCCESS = "USER_SUBSCRIPTIONS_SUCCESS";
export const USER_SUBSCRIPTIONS_FAILURE = "USER_SUBSCRIPTIONS_FAILURE";

export const USER_LIKED_VIDEOS_REQUEST = "USER_LIKED_VIDEOS_REQUEST";
export const USER_LIKED_VIDEOS_SUCCESS = "USER_LIKED_VIDEOS_SUCCESS";
export const USER_LIKED_VIDEOS_FAILURE = "USER_LIKED_VIDEOS_FAILURE";
