export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOG_OUT = "LOG_OUT";
export const GET_USER_PROFILE = "GET_USER_PROFILE";

export const HOME_VIDEOS_REQUEST = "HOME_VIDEOS_REQUEST";
export const HOME_VIDEOS_SUCCESS = "HOME_VIDEOS_SUCCESS";
export const HOME_VIDEOS_FAILURE = "HOME_VIDEOS_FAILURE";

export const SPECIFIC_VIDEO_REQUEST = "SPECIFIC_VIDEO_REQUEST";
export const SPECIFIC_VIDEO_SUCCESS = "SPECIFIC_VIDEO_SUCCESS";
export const SPECIFIC_VIDEO_FAILURE = "SPECIFIC_VIDEO_FAILURE";

export const CHANNEL_DETAILS_REQUEST = "CHANNEL_DETAILS_REQUEST";
export const CHANNEL_DETAILS_SUCCESS = "CHANNEL_DETAILS_SUCCESS";
export const CHANNEL_DETAILS_FAILURE = "CHANNEL_DETAILS_FAILURE";

export const CHANNEL_SUBSCRIPTION_STATUS_REQUEST =
  "CHANNEL_SUBSCRIPTION_STATUS_REQUEST";
export const CHANNEL_SUBSCRIPTION_STATUS_SUCCESS =
  "CHANNEL_SUBSCRIPTION_STATUS_SUCCESS";
export const CHANNEL_SUBSCRIPTION_STATUS_FAILURE =
  "CHANNEL_SUBSCRIPTION_STATUS_FAILURE";
